# Generated by Django 3.0.5 on 2021-07-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('pulse', models.PositiveIntegerField(null=True)),
                ('saturation', models.PositiveIntegerField(null=True)),
                ('temperature', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
